from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DataProvider(Protocol):
    @property
    def name(self) -> str: ...

    def set_locale(self, locale: str) -> None: ...

    def set_seed(self, seed: int) -> None: ...

    def generate_string(
        self,
        *,
        min_length: int = 1,
        max_length: int = 100,
        charset: str | None = None,
    ) -> str: ...

    def generate_integer(self, *, min_value: int = 0, max_value: int = 999999) -> int: ...

    def generate_float(
        self,
        *,
        min_value: float = 0.0,
        max_value: float = 999999.0,
        precision: int = 2,
    ) -> float: ...

    def generate_boolean(self) -> bool: ...

    def generate_bytes(self, *, length: int = 16) -> bytes: ...

    def generate_name(self) -> str: ...

    def generate_first_name(self) -> str: ...

    def generate_last_name(self) -> str: ...

    def generate_email(self) -> str: ...

    def generate_phone(self) -> str: ...

    def generate_address(self) -> str: ...

    def generate_company(self) -> str: ...

    def generate_url(self) -> str: ...

    def generate_ipv4(self) -> str: ...

    def generate_uuid(self) -> str: ...

    def generate_date(self, *, start_year: int = 2000, end_year: int | None = None) -> str: ...

    def generate_datetime(self, *, start_year: int = 2000, end_year: int | None = None) -> str: ...

    def generate_timestamp(self) -> int: ...

    def generate_text(self, *, min_length: int = 50, max_length: int = 200) -> str: ...

    def generate_sentence(self) -> str: ...

    def generate_password(self, *, length: int = 16) -> str: ...

    def generate_choice(self, choices: list[Any]) -> Any: ...

    def generate_json(self, *, schema: dict[str, Any] | None = None) -> str: ...
