"""Data stream generator for batch generation with constraint backtracking."""

from __future__ import annotations

import random
from typing import TYPE_CHECKING, Any

from sqlseed._utils.logger import get_logger
from sqlseed.generators._protocol import ConfigurationError, GenerationError, UnknownGeneratorError

if TYPE_CHECKING:
    from collections.abc import Iterator

    from sqlseed.core.column_dag import ColumnNode
    from sqlseed.core.constraints import ConstraintSolver
    from sqlseed.core.expression import ExpressionEngine
    from sqlseed.core.mapper import GeneratorSpec
    from sqlseed.core.transform import RowTransformFn

_NATIVE_MISS = object()
logger = get_logger(__name__)


class DataStream:
    """Batch data stream generator.

    Generates data column by column following the DAG node order, and uses a
    constraint solver to enforce uniqueness constraints with a backtracking mechanism:
    when a derived column conflicts, the already-generated values of its source columns
    are rolled back and regenerated until the constraints are satisfied or the maximum
    number of retries is reached.
    """

    def __init__(
        self,
        dag_nodes: list[ColumnNode],
        provider: Any,
        expr_engine: ExpressionEngine,
        constraint_solver: ConstraintSolver,
        transform_fn: RowTransformFn | None = None,
        seed: int | None = None,
    ) -> None:
        """Initialize the data stream.

        Args:
            dag_nodes: List of column DAG nodes that determines column generation order.
            provider: Data provider instance used to generate column values.
            expr_engine: Expression engine used to evaluate derived columns.
            constraint_solver: Constraint solver used for uniqueness constraints and backtracking.
            transform_fn: Optional row transform function applied when finalizing a row.
            seed: Random seed. When set, it is also synchronized to the provider.
        """
        self._nodes = dag_nodes
        self._provider = provider
        self._expr_engine = expr_engine
        self._constraint_solver = constraint_solver
        self._transform_fn = transform_fn

        self._rng = random.Random(seed)
        if seed is not None:
            self._provider.set_seed(seed)

    def generate(
        self,
        count: int,
        batch_size: int = 5000,
    ) -> Iterator[list[dict[str, Any]]]:
        """Generate data in batches, yielding one batch at a time.

        Args:
            count: Total number of rows to generate.
            batch_size: Number of rows per batch. Defaults to 5000.

        Yields:
            A list of generated rows for each batch. Each row is a dict mapping column names to values.
        """
        generated = 0
        while generated < count:
            current_batch_size = min(batch_size, count - generated)
            batch = [self._generate_row(row_idx=generated + i + 1) for i in range(current_batch_size)]
            yield batch
            generated += current_batch_size

    def _generate_node_value(
        self,
        node: ColumnNode,
        row: dict[str, Any],
        *,
        exclude_values: set[Any] | None = None,
    ) -> Any:
        """Generate the value for a single node.

        Derived columns are evaluated via the expression engine; other columns are
        generated by invoking the provider according to the generator spec. Expression
        evaluation failures raise ``GenerationError`` or ``ConfigurationError``.

        Args:
            node: The current column node.
            row: The currently generated row data.
            exclude_values: Optional set of values to avoid (UNIQUE-constrained
                columns). Passed through to ``_apply_generator`` so the dispatch
                layer can retry-with-exclude. ``None`` for non-UNIQUE columns or
                derived columns (which don't call the generator).

        Returns:
            The value generated for the node.
        """
        if node.is_derived and node.expression:
            deps = node.depends_on
            if len(deps) <= 1:
                # Single-column derive: value is scalar (backward compatible)
                ctx = {"row": row, "value": row.get(deps[0]) if deps else None}
            else:
                # Multi-column derive: value is a list of source values.
                # Users can reference via value[0], value[1] or row['col_name'].
                ctx = {"row": row, "value": [row.get(d) for d in deps]}
            try:
                return self._expr_engine.evaluate(node.expression, ctx)
            except (ValueError, SyntaxError) as exc:
                raise GenerationError(f"Expression evaluation failed: {exc}") from exc
            except (TypeError, AttributeError) as exc:
                raise ConfigurationError(f"Expression misconfigured: {exc}") from exc

        try:
            return self._apply_generator(node.generator_spec, exclude_values=exclude_values)
        except (TypeError, AttributeError) as exc:
            raise ConfigurationError(f"Generator '{node.generator_spec.generator_name}' misconfigured: {exc}") from exc
        except (ValueError, OverflowError) as exc:
            raise GenerationError(f"Generator '{node.generator_spec.generator_name}' value error: {exc}") from exc

    def _rollback_source_columns(
        self, source_columns: list[str], row: dict[str, Any], generated_values: dict[str, Any]
    ) -> None:
        """Roll back the already-generated values of source columns.

        Unregisters the source columns' registered values from the constraint solver
        and removes them from ``row`` and ``generated_values``.

        Args:
            source_columns: List of source column names to roll back.
            row: The current row data.
            generated_values: The current generated-values dict.
        """
        for bt_col in source_columns:
            if bt_col in generated_values:
                self._constraint_solver.unregister(bt_col, generated_values[bt_col])
                del generated_values[bt_col]
                row.pop(bt_col, None)

    def _attempt_node_generation(
        self, node: ColumnNode, row: dict[str, Any], generated_values: dict[str, Any]
    ) -> tuple[bool, int | None]:
        """Attempt to generate a node value and register it with the constraint solver.

        Retries generation up to the maximum retry count until registration succeeds
        or backtracking is triggered. If backtracking is triggered, the target node
        index is returned; if retries are exhausted, failure is returned.

        Args:
            node: The current column node.
            row: The current row data.
            generated_values: The current generated-values dict.

        Returns:
            A tuple ``(success, backtrack_to)`` where ``success`` indicates whether
            generation succeeded and ``backtrack_to`` is the target node index for
            backtracking or ``None``.
        """
        col_name = node.name
        max_retries = node.constraints.max_retries if node.constraints else 100
        is_unique = node.constraints.is_unique if node.constraints else False
        source_columns = node.depends_on if node.is_derived else None

        for _ in range(max_retries):
            try:
                # UNIQUE columns: pass the seen set as exclude_values so the
                # generator can avoid producing values already in use. This is
                # the root-cause fix for the "UNIQUE + semantic generators"
                # failure pattern where faker.email() etc. produce duplicates
                # on large row counts. Non-UNIQUE columns pass None (no overhead).
                exclude = self._constraint_solver.get_seen(col_name) if is_unique else None
                val = self._generate_node_value(node, row, exclude_values=exclude)
            except GenerationError as exc:
                logger.debug(
                    "Retriable generation error",
                    column=col_name,
                    generator=node.generator_spec.generator_name,
                    error=str(exc),
                )
                return False, None

            result = self._constraint_solver.try_register(
                col_name,
                val,
                is_unique=is_unique,
                source_columns=source_columns,
            )

            if result.is_registered:
                row[col_name] = val
                generated_values[col_name] = val
                return True, None

            if result.should_backtrack and source_columns:
                self._rollback_source_columns(source_columns, row, generated_values)
                bt_idx = self._find_node_index(source_columns[0])
                return False, bt_idx

        if is_unique:
            logger.warning(
                "Node exhausted retries on UNIQUE constraint",
                column=col_name,
                generator=node.generator_spec.generator_name,
                max_retries=max_retries,
            )
        return False, None

    def _handle_col_failure(
        self, backtrack_to: int | None, row: dict[str, Any], generated_values: dict[str, Any]
    ) -> None:
        """Handle column generation failure.

        When there is no backtracking target, all generated values are cleared and
        unregistered from the constraint solver. When a backtracking target exists,
        the caller is responsible for regenerating the corresponding columns.

        Args:
            backtrack_to: Target node index for backtracking or ``None``.
            row: The current row data.
            generated_values: The current generated-values dict.
        """
        if backtrack_to is None:
            for col, val in generated_values.items():
                self._constraint_solver.unregister(col, val)
            generated_values.clear()
            row.clear()

    def _finalize_row(self, row: dict[str, Any], row_idx: int, total_retries: int) -> dict[str, Any]:
        """Finalize the row by applying the transform function.

        If ``transform_fn`` is callable, it is invoked with the row and a context
        (row number, retry count) to apply the transformation; otherwise the row is
        returned unchanged.

        Args:
            row: The generated row data.
            row_idx: Row number (starting from 1).
            total_retries: Cumulative retry count for this row.

        Returns:
            The finalized row data.
        """
        if self._transform_fn:
            if callable(self._transform_fn):
                ctx = {"row_number": row_idx, "retry_count": total_retries}
                return self._transform_fn(row, ctx)
            logger.warning("transform_fn is not callable, skipping transformation")
        return row

    def _attempt_row_generation(self, row: dict[str, Any], generated_values: dict[str, Any]) -> tuple[bool, int | None]:
        """Attempt to generate an entire row.

        Iterates over nodes in DAG order, generating column by column, and handles
        skipped nodes and backtracking. On any column failure, ``_handle_col_failure``
        is invoked and the function returns early.

        Args:
            row: The current row data.
            generated_values: The current generated-values dict.

        Returns:
            A tuple ``(success, backtrack_to)`` where ``success`` indicates whether
            generation succeeded and ``backtrack_to`` is the target node index for
            backtracking or ``None``.
        """
        backtrack_to: int | None = None
        for idx, node in enumerate(self._nodes):
            if node.is_skip or (backtrack_to is not None and idx < backtrack_to):
                continue

            col_succeeded, new_backtrack_to = self._attempt_node_generation(node, row, generated_values)

            if new_backtrack_to is not None:
                backtrack_to = new_backtrack_to

            if not col_succeeded:
                self._handle_col_failure(backtrack_to, row, generated_values)
                return False, backtrack_to

        return True, backtrack_to

    def _generate_row(self, *, row_idx: int) -> dict[str, Any]:
        """Generate a single row, including the retry and backtracking mechanism.

        Retries up to the maximum total retry count (1000). When backtracking is
        triggered, the retry counter is incremented. On success, ``_finalize_row``
        applies the transform function.

        Args:
            row_idx: Row number (starting from 1).

        Returns:
            The generated row data.

        Raises:
            RuntimeError: Raised when constraints cannot be satisfied after the
                maximum number of retries.
        """
        max_total_retries = 1000
        total_retries = 0

        while total_retries < max_total_retries:
            row: dict[str, Any] = {}
            generated_values: dict[str, Any] = {}

            success, backtrack_to = self._attempt_row_generation(row, generated_values)

            if backtrack_to is not None:
                total_retries += 1
                if total_retries <= 3:
                    logger.debug(
                        "Row generation backtrack",
                        row_idx=row_idx,
                        retry=total_retries,
                        backtrack_to=backtrack_to,
                    )
                continue

            if generated_values or not any(not n.is_skip for n in self._nodes):
                return self._finalize_row(row, row_idx, total_retries)

            if total_retries <= 3:
                logger.debug(
                    "Row generation produced no values",
                    row_idx=row_idx,
                    retry=total_retries,
                    success=success,
                )
            total_retries += 1

        non_skip_nodes = [n.name for n in self._nodes if not n.is_skip]
        unique_nodes = [
            f"{n.name}(generator={n.generator_spec.generator_name!r})"
            for n in self._nodes
            if not n.is_skip and n.constraints and n.constraints.is_unique
        ]
        detail = f" Unique-constraint columns: {unique_nodes}" if unique_nodes else ""
        raise RuntimeError(
            f"Failed to generate row satisfying all constraints after {max_total_retries} retries. "
            f"Non-skip columns: {non_skip_nodes}.{detail}"
        )

    def _find_node_index(self, col_name: str) -> int | None:
        """Find the node index for a given column name.

        Args:
            col_name: Column name.

        Returns:
            The index of the node in ``self._nodes``, or ``None`` if not found.
        """
        for i, node in enumerate(self._nodes):
            if node.name == col_name:
                return i
        return None

    def _apply_generator(self, spec: GeneratorSpec, *, exclude_values: set[Any] | None = None) -> Any:
        """Apply a generator spec to produce a value.

        Processing order:
        1. If ``null_ratio`` hits, return ``None``;
        2. Try a native method (direct faker/mimesis call) — skipped when
           ``exclude_values`` is non-empty, because native methods don't
           support exclude and would bypass the dispatch-layer retry loop;
        3. Call ``provider.generate`` for regular generation, passing
           ``exclude_values`` for UNIQUE-aware retry;
        4. On ``UnknownGeneratorError``, ``choice`` falls back to local random and
           ``foreign_key`` is handled by the foreign-key routine.

        Args:
            spec: Generator spec.
            exclude_values: Optional set of values to avoid (UNIQUE-constrained
                columns). Passed to ``provider.generate`` for the dispatch
                layer's retry-with-exclude logic.

        Returns:
            The generated value.
        """
        if spec.null_ratio > 0 and self._rng.random() < spec.null_ratio:
            return None

        # Skip native method when exclude_values is needed — native methods
        # (faker/mimesis direct calls via native_faker_method/native_mimesis_method)
        # don't support exclude_values, so we fall through to the dispatch
        # layer's retry-with-exclude logic which does.
        if not exclude_values:
            native_result = self._try_native_method(spec)
            if native_result is not _NATIVE_MISS:
                return native_result

        try:
            if spec.params:
                return self._provider.generate(spec.generator_name, exclude_values=exclude_values, **spec.params)
            return self._provider.generate(spec.generator_name, exclude_values=exclude_values)
        except UnknownGeneratorError:
            if spec.generator_name == "choice" and "choices" in spec.params:
                return self._rng.choice(spec.params["choices"])

            if spec.generator_name == "foreign_key":
                return self._handle_foreign_key(spec)

            raise

    def _try_native_method(self, spec: GeneratorSpec) -> Any:
        """Attempt a native method call.

        Based on the provider name and the native method configuration in ``spec``,
        delegates to ``_try_faker_native`` or ``_try_mimesis_native``. Returns the
        ``_NATIVE_MISS`` sentinel when no method matches.

        Args:
            spec: Generator spec.

        Returns:
            The value produced by the native method, or ``_NATIVE_MISS``.
        """
        native_params = spec.native_params or {}
        if spec.native_faker_method and self._provider.name == "faker":
            result = self._try_faker_native(spec.native_faker_method, native_params)
            if result is not _NATIVE_MISS:
                return result
        if spec.native_mimesis_method and self._provider.name == "mimesis":
            result = self._try_mimesis_native(spec.native_mimesis_method, native_params)
            if result is not _NATIVE_MISS:
                return result
        return _NATIVE_MISS

    def _try_faker_native(self, method_name: str, native_params: dict[str, Any]) -> Any:
        """Attempt a faker native method.

        Retrieves the method from the provider's ``_faker`` attribute and invokes it.
        Returns ``_NATIVE_MISS`` on failure.

        Args:
            method_name: Faker method name.
            native_params: Parameters passed to the method.

        Returns:
            The value produced by the faker method, or ``_NATIVE_MISS``.
        """
        faker_obj = getattr(self._provider, "_faker", None)
        if faker_obj is None:
            return _NATIVE_MISS
        method = getattr(faker_obj, method_name, None)
        if method is None or not callable(method):
            return _NATIVE_MISS
        try:
            return method(**native_params)
        except (TypeError, ValueError, AttributeError):
            return _NATIVE_MISS

    def _try_mimesis_native(self, method_path: str, native_params: dict[str, Any]) -> Any:
        """Attempt a mimesis native method.

        Retrieves the method from the provider's ``_generic`` attribute by walking the
        dotted path component by component and invokes it. Returns ``_NATIVE_MISS`` on failure.

        Args:
            method_path: Mimesis method path (e.g. "person.full_name").
            native_params: Parameters passed to the method.

        Returns:
            The value produced by the mimesis method, or ``_NATIVE_MISS``.
        """
        generic_obj = getattr(self._provider, "_generic", None)
        if generic_obj is None:
            return _NATIVE_MISS
        parts = method_path.split(".")
        obj = generic_obj
        for part in parts:
            obj = getattr(obj, part, None)
            if obj is None:
                return _NATIVE_MISS
        if obj is None or not callable(obj):
            return _NATIVE_MISS
        try:
            return obj(**native_params)
        except (TypeError, ValueError, AttributeError):
            return _NATIVE_MISS

    def _handle_foreign_key(self, spec: GeneratorSpec) -> Any:
        """Handle foreign-key generation.

        If ``spec.params`` contains ``_ref_values``, a value is randomly chosen from it;
        otherwise an integer between ``_fallback_min`` and ``_fallback_max`` is generated.
        These fallback bounds are preserved from the original user-configured spec
        (or the mapper's pattern-matched defaults) during FK upgrade in
        ``RelationResolver._upgrade_fk_constrained_columns``, so empty-parent-table
        fallback respects the user's intended value range instead of using 999999.

        Args:
            spec: Generator spec.

        Returns:
            The foreign-key value.
        """
        ref_values = spec.params.get("_ref_values", [])
        if ref_values:
            return self._rng.choice(ref_values)
        fallback_min = spec.params.get("_fallback_min", 1)
        fallback_max = spec.params.get("_fallback_max", 999999)
        return self._provider.generate("integer", min_value=fallback_min, max_value=fallback_max)
