"""Build and manage the demo SQLite database for sqlseed tutorials.

This module serves dual purpose:
  1. **Importable library** — notebooks call ``ensure_db()`` to get a ready DB
  2. **CLI script** — ``python build_demo_db.py`` for standalone use

Public API:
  - ``ensure_db()`` — idempotent: creates schema if missing, returns path if exists
  - ``build()``     — always creates a fresh DB (destructive)
  - ``SCHEMA_SQL``  — the schema DDL, single source of truth

Design decision: **schema only, no seed data**. All data is generated by
sqlseed in the notebooks — this ensures randomness and better demonstrates
the library's capabilities.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

# ---------------------------------------------------------------------------
# Schema — single source of truth for all notebooks
# ---------------------------------------------------------------------------

SCHEMA_SQL = """\
-- Schema version: 2

-- 1. organizations — VARCHAR PK, self-ref FK, _code/_count/_at/is_ columns
CREATE TABLE IF NOT EXISTS organizations (
    org_code VARCHAR(16) PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    parent_code VARCHAR(16),
    description TEXT,
    is_active INTEGER DEFAULT 1,
    member_count INTEGER DEFAULT 0,
    created_at TEXT,
    FOREIGN KEY (parent_code) REFERENCES organizations(org_code)
);

-- 2. members — UNIQUE email, _no column, is_ boolean, BLOB, _at, REAL, explicit FK
CREATE TABLE IF NOT EXISTS members (
    member_id INTEGER PRIMARY KEY AUTOINCREMENT,
    member_no VARCHAR(16) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(128) NOT NULL UNIQUE,
    phone VARCHAR(20),
    org_code VARCHAR(16) NOT NULL,
    is_active INTEGER DEFAULT 1,
    balance REAL DEFAULT 0.0,
    avatar BLOB,
    registered_at TEXT,
    address TEXT,
    FOREIGN KEY (org_code) REFERENCES organizations(org_code)
);

-- 3. projects — _no column, UNIQUE, derive_from target, _count/_at/is_, REAL, explicit FK
CREATE TABLE IF NOT EXISTS projects (
    project_id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_no VARCHAR(20) NOT NULL UNIQUE,
    short_code VARCHAR(6),
    name VARCHAR(128) NOT NULL,
    org_code VARCHAR(16) NOT NULL,
    budget REAL DEFAULT 0.0,
    task_count INTEGER DEFAULT 0,
    is_public INTEGER DEFAULT 0,
    is_archived INTEGER DEFAULT 0,
    created_at TEXT,
    description TEXT,
    FOREIGN KEY (org_code) REFERENCES organizations(org_code)
);

-- 4. tasks — explicit FK (double), _at/is_/_count, REAL
CREATE TABLE IF NOT EXISTS tasks (
    task_id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    assignee_id INTEGER NOT NULL,
    title VARCHAR(256) NOT NULL,
    priority INTEGER DEFAULT 1,
    status INTEGER DEFAULT 0,
    is_completed INTEGER DEFAULT 0,
    comment_count INTEGER DEFAULT 0,
    estimated_hours REAL,
    due_at TEXT,
    completed_at TEXT,
    created_at TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(project_id),
    FOREIGN KEY (assignee_id) REFERENCES members(member_id)
);

-- 5. reviews — explicit FK (task_id) + implicit FK (member_id via same-name), _at
CREATE TABLE IF NOT EXISTS reviews (
    review_id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id INTEGER NOT NULL,
    member_id INTEGER NOT NULL,
    rating INTEGER DEFAULT 0,
    content TEXT,
    created_at TEXT,
    FOREIGN KEY (task_id) REFERENCES tasks(task_id)
);

-- 6. tags — simple lookup, UNIQUE name, _count
CREATE TABLE IF NOT EXISTS tags (
    tag_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(32) NOT NULL UNIQUE,
    color VARCHAR(7),
    usage_count INTEGER DEFAULT 0
);

-- 7. task_tags — multi-column UNIQUE, explicit FK (both)
CREATE TABLE IF NOT EXISTS task_tags (
    task_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    UNIQUE(task_id, tag_id),
    FOREIGN KEY (task_id) REFERENCES tasks(task_id),
    FOREIGN KEY (tag_id) REFERENCES tags(tag_id)
);

-- 8. attachments — BLOB, explicit FK, _at
CREATE TABLE IF NOT EXISTS attachments (
    attachment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id INTEGER NOT NULL,
    file_name VARCHAR(128) NOT NULL,
    file_data BLOB,
    file_size INTEGER DEFAULT 0,
    uploaded_at TEXT,
    FOREIGN KEY (task_id) REFERENCES tasks(task_id)
);

-- Indexes (IF NOT EXISTS for idempotency)
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_short_code ON projects(short_code);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assignee_id);
CREATE INDEX IF NOT EXISTS idx_reviews_task ON reviews(task_id);
CREATE INDEX IF NOT EXISTS idx_members_active ON members(is_active) WHERE is_active = 1;
CREATE INDEX IF NOT EXISTS idx_projects_org ON projects(org_code);
"""

# Expected tables in the demo DB
_EXPECTED_TABLES = frozenset({
    "organizations", "members", "projects", "tasks",
    "reviews", "tags", "task_tags", "attachments",
})

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).resolve().parent
_DEFAULT_DB_PATH = _SCRIPT_DIR / "sqlseed_demo.db"


def ensure_db(db_path: str | Path | None = None) -> Path:
    """Ensure the demo database exists with correct schema.

    Idempotent — safe to call multiple times:
      - DB exists with all tables → returns path immediately (no data loss)
      - DB missing or schema incomplete → creates/repairs schema

    No data is inserted — notebooks use sqlseed itself to fill tables,
    ensuring every run produces fresh, random data.

    Args:
        db_path: Database path. Defaults to ``examples/sqlseed_demo.db``.

    Returns:
        Absolute path to the database file.
    """
    path = Path(db_path) if db_path else _DEFAULT_DB_PATH

    if path.exists():
        conn = sqlite3.connect(str(path))
        existing = {
            r[0]
            for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()
        }
        if _EXPECTED_TABLES.issubset(existing):
            conn.close()
            return path.resolve()
        # Schema incomplete — repair
        conn.executescript(SCHEMA_SQL)
        conn.commit()
        conn.close()
        return path.resolve()

    # DB doesn't exist — create schema only
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path))
    conn.executescript(SCHEMA_SQL)
    conn.commit()
    conn.close()
    return path.resolve()


def build(db_path: str | Path | None = None) -> Path:
    """Create a fresh demo database (destructive — deletes existing).

    For a non-destructive alternative, use ``ensure_db()``.

    Args:
        db_path: Output path. Defaults to ``examples/sqlseed_demo.db``.

    Returns:
        Path to the created database file.
    """
    path = Path(db_path) if db_path else _DEFAULT_DB_PATH
    if path.exists():
        path.unlink()

    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path))
    conn.executescript(SCHEMA_SQL)
    conn.commit()
    conn.close()
    return path.resolve()


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Build sqlseed_demo.db")
    parser.add_argument("--fresh", action="store_true", help="Force rebuild (delete existing)")
    parser.add_argument("--output", default=None, help="Output path (default: examples/sqlseed_demo.db)")
    args = parser.parse_args()

    if args.fresh:
        p = build(args.output)
        print(f"Built (fresh): {p}")
    else:
        p = ensure_db(args.output)
        print(f"Ensured: {p}")
